## Objective: The objective of this assignment is to gain practical experience with fundamental operations in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on tensors, and understanding the difference between TensorFlow constants and variables.

## Part 1: Theoretical Questions

### 1. What are the different data structures used in Tensorflow?. Give some examples.

In TensorFlow, data is represented and manipulated using various data structures. Some of the commonly used data structures in TensorFlow are:

1. **Tensors**: Tensors are the primary data structures in TensorFlow. They are similar to multi-dimensional arrays and can be used for representing scalars, vectors, matrices, and higher-dimensional data. Tensors can be constants (immutable) or variables (mutable). TensorFlow uses tensors for all computations and operations. Examples:

```python
import tensorflow as tf

# Scalar tensor (rank-0 tensor)
scalar = tf.constant(3.14)

# Vector tensor (rank-1 tensor)
vector = tf.constant([1, 2, 3, 4])

# Matrix tensor (rank-2 tensor)
matrix = tf.constant([[1, 2], [3, 4]])

# Higher-dimensional tensor (rank-3 tensor)
tensor3D = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
```

2. **Variables**: Variables are special tensors used to hold and update trainable parameters during model training. They are typically used for model weights and biases. Variables must be explicitly initialized and can be updated during training. Examples:

```python
import tensorflow as tf

# Define variables
weights = tf.Variable(tf.random.normal(shape=(10, 20), mean=0.0, stddev=0.1))
biases = tf.Variable(tf.zeros(shape=(20,)))

# Initialize variables
init = tf.compat.v1.global_variables_initializer()
with tf.compat.v1.Session() as sess:
    sess.run(init)
```

3. **Placeholders**: Placeholders are used for feeding external data into TensorFlow graphs. They are typically used in the context of TensorFlow's older session-based execution mode and are not commonly used in TensorFlow 2.x. Examples:

```python
import tensorflow as tf

# Define a placeholder for input data (shape=None means it can take any shape)
input_placeholder = tf.compat.v1.placeholder(tf.float32, shape=None)

# Perform some operation using the placeholder
output = input_placeholder + 1.0

# Execute the operation by feeding data to the placeholder
with tf.compat.v1.Session() as sess:
    result = sess.run(output, feed_dict={input_placeholder: [1.0, 2.0, 3.0]})
    print(result)  # Output: [2. 3. 4.]
```

4. **Datasets**: TensorFlow's Dataset API provides an efficient and convenient way to work with large-scale data during training. Datasets allow you to represent collections of data elements (e.g., images, text samples) and apply various transformations to them. Examples:

```python
import tensorflow as tf

# Create a dataset from a Python list
data = [1, 2, 3, 4, 5]
dataset = tf.data.Dataset.from_tensor_slices(data)

# Apply transformations to the dataset
dataset = dataset.map(lambda x: x * 2)

# Iterate through the dataset
for item in dataset:
    print(item.numpy())  # Output: 2, 4, 6, 8, 10
```

These are some of the primary data structures used in TensorFlow for representing and manipulating data during model construction, training, and inference. TensorFlow provides a rich set of functions and operations to work with these data structures effectively.

### 2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.

In TensorFlow, both constants and variables are used to store data, but they have different characteristics and purposes.

**TensorFlow Constants**:
A TensorFlow constant is an immutable tensor whose value cannot be changed after it is initialized. Once a constant is created, its value remains the same throughout the execution of the TensorFlow graph. Constants are typically used for storing fixed data that does not change during training, such as hyperparameters or fixed input data.

**Example of TensorFlow Constants**:
```python
import tensorflow as tf

# Define TensorFlow constants
a = tf.constant(2.0)
b = tf.constant(3.0)

# Perform some operations using the constants
sum_ab = a + b
product_ab = a * b

# Run the TensorFlow session to evaluate the operations
with tf.compat.v1.Session() as sess:
    result_sum_ab = sess.run(sum_ab)
    result_product_ab = sess.run(product_ab)
    print("Sum:", result_sum_ab)  # Output: Sum: 5.0
    print("Product:", result_product_ab)  # Output: Product: 6.0
```

**TensorFlow Variables**:
In contrast, TensorFlow variables are mutable tensors that can be used to store and update trainable parameters during model training. Variables are typically used for model weights and biases, which need to be updated during the optimization process. Variables must be explicitly initialized and can be modified during training.

**Example of TensorFlow Variables**:
```python
import tensorflow as tf

# Define TensorFlow variables
weights = tf.Variable(tf.random.normal(shape=(2, 3), mean=0.0, stddev=0.1))
biases = tf.Variable(tf.zeros(shape=(3,)))

# Initialize variables
init = tf.compat.v1.global_variables_initializer()
with tf.compat.v1.Session() as sess:
    sess.run(init)

# Update variables during training (example)
new_weights = tf.Variable(tf.ones(shape=(2, 3)))
update_op = weights.assign(new_weights)

# Run the TensorFlow session to perform the update
with tf.compat.v1.Session() as sess:
    sess.run(update_op)
    updated_weights = sess.run(weights)
    print("Updated Weights:", updated_weights)
```

**Differences Summary**:
1. Constants are immutable and have fixed values throughout the execution, while variables are mutable and can be updated during training.
2. Constants are used for storing fixed data, while variables are used for storing trainable parameters like model weights and biases.
3. Constants do not require explicit initialization, while variables must be initialized before using them in the session.

In summary, TensorFlow constants and variables serve different purposes in deep learning models. Constants are used for fixed data, while variables are used for trainable parameters that need to be updated during training. Understanding these differences is crucial when designing and training TensorFlow models effectively.

### 3. Describe the process of matrix addition, multiplication, and elements wise operations in TensorFlow

Ans--> In TensorFlow, matrix addition, multiplication, and element-wise operations are fundamental mathematical operations used in various deep learning models and computations. These operations are performed using tensors, which are the primary data structures in TensorFlow. Here's an overview of each process:

1. **Matrix Addition**:
Matrix addition involves adding two matrices element-wise. To perform matrix addition in TensorFlow, you can use the `tf.add()` function or the `+` operator.

In [2]:
%pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 2.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 56.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 77.9 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 79.1 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 67.1 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 73.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 22.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 13.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 24.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 78.9 MB/s eta

In [4]:
import tensorflow as tf

# Define two matrices as constants
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition using the `tf.add()` function
result_add = tf.add(matrix_a, matrix_b)

# Alternatively, perform matrix addition using the `+` operator
result_add_alt = matrix_a + matrix_b

# Run the TensorFlow session to evaluate the result
with tf.compat.v1.Session() as sess:
    print("Result (using tf.add()):")
    print(result_add)
    print("Result (using + operator):")
    print(result_add_alt)

Result (using tf.add()):
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Result (using + operator):
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


2. **Matrix Multiplication**:
Matrix multiplication involves multiplying two matrices to produce a new matrix. In TensorFlow, you can use the `tf.matmul()` function for matrix multiplication.

In [5]:
import tensorflow as tf

# Define two matrices as constants
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication using the `tf.matmul()` function
result_multiply = tf.matmul(matrix_a, matrix_b)

# Run the TensorFlow session to evaluate the result
with tf.compat.v1.Session() as sess:
    print("Result (matrix multiplication):")
    print(result_multiply)

Result (matrix multiplication):
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


3. **Element-wise Operations**:
Element-wise operations involve applying an operation to each element of a tensor independently. In TensorFlow, you can use various element-wise functions like `tf.add()`, `tf.subtract()`, `tf.multiply()`, `tf.divide()`, etc.

In [6]:
import tensorflow as tf

# Define a matrix as a constant
matrix = tf.constant([[1, 2], [3, 4]])

# Perform element-wise operations
result_add = tf.add(matrix, 2)  # Add 2 to each element
result_subtract = tf.subtract(matrix, 1)  # Subtract 1 from each element
result_multiply = tf.multiply(matrix, 3)  # Multiply each element by 3
result_divide = tf.divide(matrix, 2)  # Divide each element by 2

# Run the TensorFlow session to evaluate the results
with tf.compat.v1.Session() as sess:
    print("Result (element-wise addition):")
    print(result_add)
    print("Result (element-wise subtraction):")
    print(result_subtract)
    print("Result (element-wise multiplication):")
    print(result_multiply)
    print("Result (element-wise division):")
    print(result_divide)

Result (element-wise addition):
tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)
Result (element-wise subtraction):
tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int32)
Result (element-wise multiplication):
tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
Result (element-wise division):
tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


In summary, matrix addition, multiplication, and element-wise operations are essential mathematical operations used in TensorFlow. These operations are performed on tensors, and TensorFlow provides various functions and operators to execute these operations efficiently.

## Part 2: Practical Implementation

## Task 1: Creating and Manipulating Matrices.

### 1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.

In [21]:
import tensorflow as tf

In [42]:
# Creating the matrix A
A=tf.random.normal(shape=(3,3))

In [43]:
# Display the matrix
print(A)

tf.Tensor(
[[ 0.8615175  -0.9199439   0.7258465 ]
 [-2.1555352   1.1120759   0.22391117]
 [ 0.27071527  0.45288032 -0.3192282 ]], shape=(3, 3), dtype=float32)


### 2. Create a Gaussian matrix B with dimensions 4x,4 using TensorFlow's truncated_normal function. Display the values of matrix B.

In [24]:
B=tf.random.truncated_normal(shape=(4,4),mean=0.0,stddev=1.0)

In [25]:
# Display the value of matrix B
print(B)

tf.Tensor(
[[-0.831235   -0.180148    0.7479372   1.0210761 ]
 [ 1.0180545   0.22476287 -1.2323446  -0.48305613]
 [ 0.4536549   0.6536843  -0.35191333 -1.3512433 ]
 [-0.79390967 -1.6790526   0.50433373  0.16613099]], shape=(4, 4), dtype=float32)


### 3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.

In [26]:
mean=2
stddev=0.5

C=tf.random.normal(shape=(2,2),mean=mean,stddev=stddev)

In [27]:
# Display the value of matrix C
print(C)

tf.Tensor(
[[2.2604613 1.2711923]
 [2.4598525 2.0281   ]], shape=(2, 2), dtype=float32)


### 4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.

In [44]:
# Add the extra padding in matrix A for addition
A_resize=tf.pad(A,paddings=[[0,1],[0,1]])

In [45]:
# Addition of the matrix
D=tf.add(A_resize,B)

In [46]:
print(D)

tf.Tensor(
[[ 0.0302825  -1.1000919   1.4737837   1.0210761 ]
 [-1.1374807   1.3368388  -1.0084335  -0.48305613]
 [ 0.7243701   1.1065646  -0.6711415  -1.3512433 ]
 [-0.79390967 -1.6790526   0.50433373  0.16613099]], shape=(4, 4), dtype=float32)


### 5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [50]:
# Add the extra paddding in matrix C for multiplication
C_resize=tf.pad(C,paddings=[[0,0],[0,2]])

In [52]:
E=tf.matmul(C_resize,D)

In [53]:
print(E)

tf.Tensor(
[[-1.3775043  -0.7873361   2.049518    1.6940458 ]
 [-2.232434    0.00517917  1.5800867   1.5320104 ]], shape=(2, 4), dtype=float32)


## Task 2: Performing Additional Matrix Operations

### 1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.

In [58]:
F=tf.random.uniform(shape=(3,3))

In [59]:
print(F)

tf.Tensor(
[[0.017169   0.03528774 0.88752043]
 [0.8403144  0.4043224  0.5119927 ]
 [0.14254344 0.5471339  0.8085282 ]], shape=(3, 3), dtype=float32)


### 2. Calculate the transpose of matrix F and store the result in matrix G.

In [60]:
G=tf.transpose(F)

In [61]:
print(G)

tf.Tensor(
[[0.017169   0.8403144  0.14254344]
 [0.03528774 0.4043224  0.5471339 ]
 [0.88752043 0.5119927  0.8085282 ]], shape=(3, 3), dtype=float32)


### 3. Calculate the element-wise exponential of matrix F and store the result in matrix H.

In [62]:
H=tf.exp(F)

In [63]:
print(H)

tf.Tensor(
[[1.0173172 1.0359178 2.429099 ]
 [2.3170953 1.4982868 1.668613 ]
 [1.1532031 1.7282925 2.244602 ]], shape=(3, 3), dtype=float32)


### 4. Create a matrix I by concatenating matrix F and matrix G horizontally.

In [64]:
I=tf.concat([F,G],axis=1)

In [65]:
print(I)

tf.Tensor(
[[0.017169   0.03528774 0.88752043 0.017169   0.8403144  0.14254344]
 [0.8403144  0.4043224  0.5119927  0.03528774 0.4043224  0.5471339 ]
 [0.14254344 0.5471339  0.8085282  0.88752043 0.5119927  0.8085282 ]], shape=(3, 6), dtype=float32)


### 5. Create a matrix J by concatenating matrix F and matrix H vertically.

In [66]:
J=tf.concat([F,H],axis=0)

In [67]:
print(J)

tf.Tensor(
[[0.017169   0.03528774 0.88752043]
 [0.8403144  0.4043224  0.5119927 ]
 [0.14254344 0.5471339  0.8085282 ]
 [1.0173172  1.0359178  2.429099  ]
 [2.3170953  1.4982868  1.668613  ]
 [1.1532031  1.7282925  2.244602  ]], shape=(6, 3), dtype=float32)
